### ISSUE TITLE
Still puzzled about your PMI-domain...

### ISSUE THREAD

**Issue by MM-IR** [peterwestuw/surface-form-competition#4]
Hi, I am very interested in this work. It seems to alleviate the issues of surface form competition by proposing another scoring function, e.g. PMI-domain. The domain premise can be a prompt for classification tasks. I still think this method is more like a calibration technique... Or do I have any misunderstandings? How can we resolve the surface form competition issue in our LM predicted distribution?

Thanks for your help!

**Comment by ari-holtzman** [comment]
Answered over email.
